x-otel-common:
  &otel-common
  OTEL_LOG_LEVEL: warning
  OTEL_TRACES_SAMPLER: parentbased_always_on
  OTEL_TRACES_EXPORTER: otlp
  OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: grpc
  OTEL_EXPORTER_OTLP_ENDPOINT: signoz:4317  # Replace with SigNoz OTLP endpoint, if SigNoz not running on host machine
  OTEL_EXPORTER_OTLP_INSECURE: true
  OTEL_TRACES_PROCESSOR: simple

version: '3.7'
services:
  golang:
    image: golang:bullseye
    working_dir: /opt/app
    command: [ 'go', 'run', 'main.go' ]
    volumes:
      - './:/opt/app'
    ports:
      - '8090:8090'
    extra_hosts:
      - signoz:host-gateway
    environment:
      <<: *otel-common
      SERVICE_NAME: golang
      INSECURE_MODE: true
      RESOURCE_ATTRIBUTES: 'service.version=0.1'
